import { SecuritiesAccount } from "../../types/types";

export const dummylist: SecuritiesAccount[] = [
  {
    id: 1,
    id_customer: "ABC123",
    kode_bk: "KBK456",
    no_rekening_investor: "INV789",
    nama_perusahaan: "Dummy Company 1",
    nama_awal: "John",
    nama_tengah: "",
    nama_belakang: "Doe",
    ktp: "1234567890",
    npwp: "NPWP123",
    no_paspor: "PASS456",
    no_pendaftaran_usaha: "REG789",
    tanggal_pendirian: null,
    tempat_penidiran: "Some Location",
    tipe_investor: "Type A",
    jenis_kelamin: "Male",
    jenis_pekerjaan: "Job Type X",
    alamat_identitas_1: "Address Line 1",
    alamat_identitas_2: "Address Line 2",
    kode_kota: "CityCode123",
    kode_provinsi: "ProvinceCode456",
    kode_negara: "CountryCode789",
    no_telepon: "123456789",
    no_hp: "987654321",
    email: "john.doe@example.com",
    // created_at: new Date("2023-11-15"),
    updated_at: null,
  },
  {
    id: 2,
    id_customer: "DEF456",
    kode_bk: "KBK789",
    no_rekening_investor: "INV987",
    nama_perusahaan: "Dummy Company 2",
    nama_awal: "Jane",
    nama_tengah: "",
    nama_belakang: "Smith",
    ktp: "0987654321",
    npwp: "NPWP456",
    no_paspor: "PASS789",
    no_pendaftaran_usaha: "REG987",
    tanggal_pendirian: null,
    tempat_penidiran: "Another Location",
    tipe_investor: "Type B",
    jenis_kelamin: "Female",
    jenis_pekerjaan: "Job Type Y",
    alamat_identitas_1: "Address Line 3",
    alamat_identitas_2: "Address Line 4",
    kode_kota: "CityCode456",
    kode_provinsi: "ProvinceCode789",
    kode_negara: "CountryCode012",
    no_telepon: "987654321",
    no_hp: "123456789",
    email: "jane.smith@example.com",
    // created_at: new Date("2023-11-14"),
    // updated_at: new Date("2023-11-15"),
  },
  {
    id: 3,
    id_customer: "GHI789",
    kode_bk: "KBK012",
    no_rekening_investor: "INV345",
    nama_perusahaan: "Dummy Company 3",
    nama_awal: "Alice",
    nama_tengah: "",
    nama_belakang: "Johnson",
    ktp: "1357924680",
    npwp: "NPWP789",
    no_paspor: "PASS012",
    no_pendaftaran_usaha: "REG012",
    tanggal_pendirian: null,
    tempat_penidiran: "Different Location",
    tipe_investor: "Type C",
    jenis_kelamin: "Female",
    jenis_pekerjaan: "Job Type Z",
    alamat_identitas_1: "Address Line 5",
    alamat_identitas_2: "Address Line 6",
    kode_kota: "CityCode789",
    kode_provinsi: "ProvinceCode012",
    kode_negara: "CountryCode345",
    no_telepon: "543216789",
    no_hp: "987612345",
    email: "alice.johnson@example.com",
    // created_at: new Date("2023-11-13"),
    // updated_at: null,
  },
];
