  export interface iSecurities {
    id: null,
    id_customer: string,
    kode_bk: string,
    no_rekening_investor: string,
    nama_perusahaan: string,
    nama_awal: string,
    nama_tengah: string,
    nama_belakang: string,
    ktp: string,
    npwp: string,
    no_paspor: string,
    no_pendaftaran_usaha: string,
    tanggal_pendirian: any,
    tempat_penidiran: any,
    tipe_investor: string,
    jenis_kelamin: string,
    jenis_pekerjaan: string,
    alamat_identitas_1: string,
    alamat_identitas_2: string,
    kode_kota: string,
    kode_provinsi: string,
    kode_negara: string,
    no_telepon: string,
    no_hp: string,
    email: string,

  }
  